[start]
command:/usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script
message:start kea-unbound ddns listener

[stop]
command:/usr/local/opnsense/scripts/keaunbound/stop.py
parameters:
type:script
message:stop kea-unbound ddns listener

[restart]
command:/usr/local/opnsense/scripts/keaunbound/start.py
parameters:
type:script
message:restart kea-unbound ddns listener

[status]
command:/usr/local/sbin/pluginctl -s keaunbound status
parameters:
type:script_output
message:get kea-unbound ddns listener status

[sync]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/keaunbound/lease-sync.py
parameters:
type:script_output
message:seed existing kea leases and reservations into unbound
